version: '3.8'
services:
  mongo:
    image: mongo:7.0
    container_name: hcx-mongo-db
    env_file:
      - ../.env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  mongo-data: