export const ACT_REASON_CS = 'http://terminology.hl7.org/CodeSystem/v3-ActReason';
export const COMM_CATEGORY_CS = 'http://terminology.hl7.org/CodeSystem/communication-category';
export const PARTICIPATION_MODE_CS = 'http://terminology.hl7.org/CodeSystem/v3-ParticipationMode';

export const reasonCodes = [
  { code: 'MEDNEC', display: 'Medical Necessity', system: ACT_REASON_CS },
  { code: 'CLINREV', display: 'Clinical Review', system: ACT_REASON_CS },
  { code: 'PATADMIN', display: 'Patient Administration', system: ACT_REASON_CS },
  { code: 'VERIFY', display: 'Verification Required', system: ACT_REASON_CS },
  { code: 'ELIGVER', display: 'Eligibility Verification', system: ACT_REASON_CS },
  { code: 'PATREQ', display: 'Patient Request', system: ACT_REASON_CS },
  { code: 'COVAUTH', display: 'Coverage Authorization', system: ACT_REASON_CS },
  { code: 'FINREV', display: 'Financial Review', system: ACT_REASON_CS },
];

export const categories = [
  { code: 'alert', display: 'Alert', system: COMM_CATEGORY_CS },
  { code: 'instruction', display: 'Instruction', system: COMM_CATEGORY_CS },
  { code: 'notification', display: 'Notification', system: COMM_CATEGORY_CS },
  { code: 'reminder', display: 'Reminder', system: COMM_CATEGORY_CS },
];

export const mediums = [
  { code: 'WRITTEN', display: 'Written (Portal/Letter)', system: PARTICIPATION_MODE_CS },
  { code: 'EMAILWRIT', display: 'Email', system: PARTICIPATION_MODE_CS },
  { code: 'FAXWRIT', display: 'Fax', system: PARTICIPATION_MODE_CS },
  { code: 'PHONE', display: 'Telephone', system: PARTICIPATION_MODE_CS },
  { code: 'VIDEOCONF', display: 'Video Conference', system: PARTICIPATION_MODE_CS },
  { code: 'VOICE', display: 'Voice (Verbal)', system: PARTICIPATION_MODE_CS },
  { code: 'FACE', display: 'In person', system: PARTICIPATION_MODE_CS },
];

export const commonMimeTypes = [
  'application/pdf',
  'image/jpeg',
  'image/png',
  'text/plain',
  'text/csv',
  'application/json',
  'application/xml',
  'application/zip',
];

export const commonLanguages = [
  { code: 'ar', display: 'Arabic' },
  { code: 'bn', display: 'Bengali' },
  { code: 'cs', display: 'Czech' },
  { code: 'da', display: 'Danish' },
  { code: 'de', display: 'German' },
  { code: 'de-AT', display: 'German (Austria)' },
  { code: 'de-CH', display: 'German (Switzerland)' },
  { code: 'de-DE', display: 'German (Germany)' },
  { code: 'el', display: 'Greek' },
  { code: 'en', display: 'English' },
  { code: 'en-AU', display: 'English (Australia)' },
  { code: 'en-CA', display: 'English (Canada)' },
  { code: 'en-GB', display: 'English (Great Britain)' },
  { code: 'en-IN', display: 'English (India)' },
  { code: 'en-NZ', display: 'English (New Zeland)' },
  { code: 'en-SG', display: 'English (Singapore)' },
  { code: 'en-US', display: 'English (United States)' },
  { code: 'es', display: 'Spanish' },
  { code: 'es-AR', display: 'Spanish (Argentina)' },
  { code: 'es-ES', display: 'Spanish (Spain)' },
  { code: 'es-UY', display: 'Spanish (Uruguay)' },
  { code: 'fi', display: 'Finnish' },
  { code: 'fr', display: 'French' },
  { code: 'fr-BE', display: 'French (Belgium)' },
  { code: 'fr-CH', display: 'French (Switzerland)' },
  { code: 'fr-FR', display: 'French (France)' },
  { code: 'fy', display: 'Frysian' },
  { code: 'fy-NL', display: 'Frysian (Netherlands)' },
  { code: 'hi', display: 'Hindi' },
  { code: 'hr', display: 'Croatian' },
  { code: 'it', display: 'Italian' },
  { code: 'it-CH', display: 'Italian (Switzerland)' },
  { code: 'it-IT', display: 'Italian (Italy)' },
  { code: 'ja', display: 'Japanese' },
  { code: 'ko', display: 'Korean' },
  { code: 'nl', display: 'Dutch' },
  { code: 'nl-BE', display: 'Dutch (Belgium)' },
  { code: 'nl-NL', display: 'Dutch (Netherlands)' },
  { code: 'no', display: 'Norwegian' },
  { code: 'no-NO', display: 'Norwegian (Norway)' },
  { code: 'pa', display: 'Punjabi' },
  { code: 'pl', display: 'Polish' },
  { code: 'pt', display: 'Portuguese' },
  { code: 'pt-BR', display: 'Portuguese (Brazil)' },
  { code: 'ru', display: 'Russian' },
  { code: 'ru-RU', display: 'Russian (Russia)' },
  { code: 'sr', display: 'Serbian' },
  { code: 'sr-RS', display: 'Serbian (Serbia)' },
  { code: 'sv', display: 'Swedish' },
  { code: 'sv-SE', display: 'Swedish (Sweden)' },
  { code: 'te', display: 'Telugu' },
  { code: 'zh', display: 'Chinese' },
  { code: 'zh-CN', display: 'Chinese (China)' },
  { code: 'zh-HK', display: 'Chinese (Hong Kong)' },
  { code: 'zh-SG', display: 'Chinese (Singapore)' },
  { code: 'zh-TW', display: 'Chinese (Taiwan)' },
];
